# update_ai_index.ps1
# Regenerates memory/ai_index/ files from current repo state and dashboard snapshot.
#
# Safety:
# - Never writes to Supabase
# - Never writes to Smartsheet
# - Never sends emails or Teams messages
# - Never exposes secrets or env var values
# - Only writes to memory/ai_index/*.md
#
# Usage:
#   From repo root:
#   .\scripts\update_ai_index.ps1
#
# Output:
#   memory/ai_index/DASHBOARD_STATUS.md  (mirrored from dashboard snapshot)
#   memory/ai_index/START_HERE_FOR_AI.md (not overwritten — manually maintained)
#   memory/ai_index/CLIENT_ROSTER.md     (not overwritten — manually maintained)
#   memory/ai_index/PROJECT_INDEX.md     (not overwritten — manually maintained)
#   memory/ai_index/OPEN_LOOPS_SUMMARY.md (not overwritten — manually maintained)
#
# Note on auto-regeneration:
#   The full PROJECT_INDEX and CLIENT_ROSTER require reading all PROJECT_CARD.md files.
#   This script currently auto-regenerates only DASHBOARD_STATUS.md from the snapshot.
#   Full index regeneration is flagged for a future version that reads Supabase directly.

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# ─── Paths ────────────────────────────────────────────────────────────────────
$repoRoot       = Split-Path $PSScriptRoot -Parent
$aiIndexDir     = Join-Path $repoRoot "memory\ai_index"
$snapshotFile   = Join-Path $repoRoot "memory\dashboard\CURRENT_DASHBOARD_STATUS.md"
$dashStatusOut  = Join-Path $aiIndexDir "DASHBOARD_STATUS.md"

# ─── Safety check: never print env vars ───────────────────────────────────────
# This script does not read Supabase env vars. No secrets are accessed.

Write-Host ""
Write-Host "=== update_ai_index.ps1 ===" -ForegroundColor Cyan
Write-Host "Repo root : $repoRoot"
Write-Host "AI index  : $aiIndexDir"
Write-Host ""

# ─── Ensure output directory exists ───────────────────────────────────────────
if (-not (Test-Path $aiIndexDir)) {
    New-Item -ItemType Directory -Path $aiIndexDir | Out-Null
    Write-Host "Created directory: $aiIndexDir" -ForegroundColor Yellow
}

# ─── Step 1: Mirror dashboard snapshot into DASHBOARD_STATUS.md ───────────────
Write-Host "Step 1 — Mirror dashboard snapshot..." -ForegroundColor Cyan

if (-not (Test-Path $snapshotFile)) {
    Write-Warning "Dashboard snapshot not found at: $snapshotFile"
    Write-Warning "Run scripts\update_dashboard_snapshot.ps1 first."
} else {
    $snapshotContent = Get-Content $snapshotFile -Raw

    # Extract Last Updated from snapshot
    $lastUpdatedMatch = [regex]::Match($snapshotContent, '\|\s*\*\*Last Updated\*\*\s*\|\s*([^\|]+)\|')
    $lastUpdated = if ($lastUpdatedMatch.Success) { $lastUpdatedMatch.Groups[1].Value.Trim() } else { "Unknown" }

    # Check staleness (warn if > 1 day old)
    $stalenessWarning = ""
    try {
        $snapshotDate = [datetime]::ParseExact($lastUpdated, "yyyy-MM-dd", $null)
        $ageInDays = ([datetime]::Today - $snapshotDate).TotalDays
        if ($ageInDays -gt 1) {
            $stalenessWarning = "`n> **WARNING: Snapshot is $([math]::Round($ageInDays, 1)) day(s) old. Counts and rows may be stale.**"
        }
    } catch {
        $stalenessWarning = "`n> **WARNING: Could not parse snapshot date. Treat as potentially stale.**"
    }

    $dashStatusContent = @"
# Dashboard Status — AI Index
_Mirrored from: memory/dashboard/CURRENT_DASHBOARD_STATUS.md_
_Mirror generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm')_

> **Staleness warning:** If today's date is more than 1 day after the snapshot Last Updated date, counts and rows are stale.$stalenessWarning
> For live data, run ``scripts\update_dashboard_snapshot.ps1`` (requires Supabase env vars).

---

$snapshotContent

---

_Mirror regenerated by: scripts\update_ai_index.ps1_
"@

    Set-Content -Path $dashStatusOut -Value $dashStatusContent -Encoding utf8
    Write-Host "  Written: $dashStatusOut" -ForegroundColor Green
}

# ─── Step 2: Scan project card count per client ───────────────────────────────
Write-Host ""
Write-Host "Step 2 — Scan project cards..." -ForegroundColor Cyan

$clientsRoot = Join-Path $repoRoot "memory\clients"
$clientDirs  = Get-ChildItem $clientsRoot -Directory | Where-Object { $_.Name -ne "_unassigned" -and $_.Name -ne "jpmc" }

$projectCount = 0
$noCardClients = @()

foreach ($client in $clientDirs) {
    $projectsDir = Join-Path $client.FullName "projects"
    if (Test-Path $projectsDir) {
        $cards = Get-ChildItem $projectsDir -Recurse -Filter "PROJECT_CARD.md"
        $projectCount += $cards.Count
        if ($cards.Count -eq 0) {
            $noCardClients += $client.Name
        }
    } else {
        $noCardClients += $client.Name
    }
}

Write-Host "  Total project cards found : $projectCount"
if ($noCardClients.Count -gt 0) {
    Write-Host "  Clients with no cards     : $($noCardClients -join ', ')" -ForegroundColor Yellow
}

# ─── Step 3: Open loops count ─────────────────────────────────────────────────
Write-Host ""
Write-Host "Step 3 — Scan open loops files..." -ForegroundColor Cyan

$openLoopsFiles = Get-ChildItem $clientsRoot -Recurse -Filter "OPEN_LOOPS.md"
Write-Host "  Open loops files found: $($openLoopsFiles.Count)"

# Count unchecked items (lines starting with "- [ ]" or "| Open |")
$openItemCount = 0
foreach ($loopFile in $openLoopsFiles) {
    $content = Get-Content $loopFile.FullName -Raw
    $openItems = [regex]::Matches($content, '(?m)^\-\s*\[\s*\]|\|\s*Open\s*\|')
    $openItemCount += $openItems.Count
}
Write-Host "  Estimated open items      : $openItemCount"

# ─── Step 4: Summary ──────────────────────────────────────────────────────────
Write-Host ""
Write-Host "=== Summary ===" -ForegroundColor Cyan
Write-Host "  DASHBOARD_STATUS.md  : Updated" -ForegroundColor Green
Write-Host "  PROJECT_INDEX.md     : Not auto-regenerated (manually maintained)" -ForegroundColor Yellow
Write-Host "  CLIENT_ROSTER.md     : Not auto-regenerated (manually maintained)" -ForegroundColor Yellow
Write-Host "  OPEN_LOOPS_SUMMARY.md: Not auto-regenerated (manually maintained)" -ForegroundColor Yellow
Write-Host "  START_HERE_FOR_AI.md : Not auto-regenerated (manually maintained)" -ForegroundColor Yellow
Write-Host ""
Write-Host "  Project cards found  : $projectCount"
Write-Host "  Open loops files     : $($openLoopsFiles.Count)"
Write-Host "  Est. open items      : $openItemCount"
Write-Host ""
Write-Host "  NOTE: To fully regenerate PROJECT_INDEX and CLIENT_ROSTER, Claude Code"
Write-Host "  should read each client folder and rebuild from current PROJECT_CARD.md files."
Write-Host "  This script updates only the dashboard mirror automatically."
Write-Host ""
Write-Host "Done." -ForegroundColor Green
